version: "3"

services:
  hadoop:
    image: big-data-env:latest
    container_name: hadoop-env
    restart: always
    ports:
      - 8088:8088
      - 8080:8080
      - 50070:50070
      - 9000:9000
    volumes:
      - ./scripts:/scripts
      - ./scripts/dags:/root/airflow/dags
      - ./mov_cartoes_flat:/mov_cartoes_flat
    env_file:
      - ./.env
    user: root
    networks: 
      - hadoop_env

  db:
    image: mysql:8.0
    container_name: mov_cartoes_db
    ports:
      - "3306:3306"
    volumes:
      - database-data:/data/mysql 
      - ./scripts/sql/mov_cartoes_ddl.sql:/docker-entrypoint-initdb.d/initdb.sql
    env_file:
      - ./.env
    restart: unless-stopped
    networks: 
      - hadoop_env

volumes:
  database-data:

networks:
  hadoop_env:
    driver: bridge
